const mongoose = require("mongoose");

const biographySchema = new mongoose.Schema({
    name: {
        type: String,
        required: true
    },
    birthDate: Date,
    nationality: String,
    occupation: String,
    bioSummary: {
        type: String,
        required: true
    }
});

const Biography = mongoose.model("Biography", biographySchema);

module.exports = Biography;

//Generated by GPT 4