const mongoose = require("mongoose");

const biographySchema = new mongoose.Schema({
    name: {
        type: String,
        required: true
    },
    birthDate: Date,
    nationality: String,
    occupation: String,
    bioSummary: {
        type: String,
        required: true
    }
});

const Biography = mongoose.model("Biography", biographySchema);
Biography.watch().on("change", data => console.log(new Date(), data));

const messi = new Biography({
    name: "Lionel Messi",
    birthDate: "1987-06-24",
    nationality: "Argentina",
    occupation: "Footballer",
    bioSummary: "GOAT"
})
//messi.save();

module.exports = Biography;

//Generated by GPT 4