const mongoose = require("mongoose");

const fileDetailsSchema = new mongoose.Schema({
    fileName: {
        type: String,
        required: true
    },
    filePath: {
        type: String,
        required: true
    },
    fileSize: Number,
    fileType: String,
    uploadDate: {
        type: Date,
        default: Date.now
    }
});

const FileDetails = mongoose.model("FileDetails", fileDetailsSchema);

module.exports = FileDetails;

//Generated by GPT 4